Hotfix/0.0.1
lunasoft/sw-sdk-php pull request #30
Opened 2022-01-17 06:21 UTC by martinfnsw

Actualización UT

2022-01-21 19:59 UTC, SwAeyrton requested changes

2022-01-23 20:52 UTC, martinfnsw commented on composer.json
> -    "name": "lunasoft/sw-sdk-php",
Gracias no me di cuenta de que estaba subiendo el archivo equivocado, ya puse el correspondiente.

2022-01-23 20:52 UTC, martinfnsw commented on SWServices/SatQuery/SatQueryRequest.php
> +                                      <tem:expresionImpresa><![CDATA[?re='.$rfcEmisor.'&rr='.$rfcReceptor.'&tt='.$total.'&id='.$uuid.'&fe='.$fe8.']]></tem:expresionImpresa>
Gracias, ya se realizó el cambio

2022-01-24 18:14 UTC, SwAeyrton approved these changes

2022-01-24 18:44 UTC, merged