Feature/pdf service
lunasoft/sw-sdk-php pull request #44
Opened 2022-11-07 22:50 UTC by martinfnsw

Se agregan clases para los servicios PDF
Se actualizan UT
Se actualiza README

2022-11-08 15:58 UTC, SwAeyrton requested changes

2022-11-08 15:58 UTC, SwAeyrton commented on SWServices/PDF/PDFHelper.php
> +    public static function get_response($response)
Este getter es innecesario.

2022-11-08 15:58 UTC, SwAeyrton commented on SWServices/PDF/PDFService.php
> +        return $helper::get_response($response);
Por lo mismo que mi comentario anterior, podria quedar solo return $response

2022-11-08 15:58 UTC, SwAeyrton commented on SWServices/PDF/PDFService.php
> +     public static function GeneratePDF($urlApi, $xml, $logo, $templateId,$extras,$isB64=false){
$urlApi ya no lo deberias solicitar como parametro porque ya lo recibes en el constructor

2022-11-08 15:58 UTC, SwAeyrton commented on SWServices/PDF/PDFHelper.php
> +    public static function get_urlApi()
A mi parecer esto deberia estar en services.php junto con los otros getters y setters.

2022-11-08 23:26 UTC, SwAeyrton requested changes

2022-11-08 23:26 UTC, SwAeyrton commented on Test/PDFTest.php
> +    public function testPDF_UrlNull()
Este test falla

2022-11-09 15:56 UTC, SwAeyrton requested changes

2022-11-09 19:05 UTC, martinfnsw commented on Test/PDFTest.php
> +			$this->assertEquals($resultSpect, $result);
Se quitaron los saltos de línea, aun así, el test no respondo como success pero si retorna el valor esperado

2022-11-10 00:21 UTC, SwAeyrton requested changes
Falta subir la version en el composer.json

2022-11-10 04:43 UTC, SwAeyrton approved these changes

2022-11-10 04:43 UTC, SwAeyrton commented on composer.json
> +    "version": "1.0.3.2",
deberia quedar como 1.0.3.1

2022-11-10 05:08 UTC, martinfnsw commented on composer.json
> +    "version": "1.0.3.2",
Cierto ya me había pasado en la de donet jaj gracias

2022-11-10 05:11 UTC, SwAeyrton approved these changes

2022-11-10 15:48 UTC, marifersw approved these changes

2022-11-10 18:35 UTC, ReyesSW approved these changes
All good.

2022-11-10 19:09 UTC, merged