Feature/stamp v4
lunasoft/sw-sdk-php pull request #45
Opened 2022-11-10 19:56 UTC by ReyesSW

Se realizan las modificaciones a la librería para agregar el TimbradoV4. 
Se crea un nuevo request para consumir el servicio.
Se crean pruebas unitarias
Se agregan en StampService las funciones para el StampV4
Se modifica el Readme para cambiar usuario y contraseña de pruebas.

2022-11-10 20:23 UTC, SwAeyrton requested changes

2022-11-10 20:23 UTC, SwAeyrton commented on composer.json
> -}
Falta actualizar la version.

2022-11-10 20:23 UTC, SwAeyrton commented on SWServices/Stamp/StampRequestV4.php
> +    public static function sendReqV4($url, $token, $xml, $version, $isb64, $proxy, $path, $customId, $customIdValue, $pdf, $email, $emailAddress){ //12 Parametros
No se requiere crear otra clase StampRequestV4, podria quedar en la misma que ya existe, StampRequest.php

2022-11-10 20:23 UTC, SwAeyrton commented on SWServices/Stamp/StampService.php
> +    public static function StampV4CustomId($xml, $customId = true, $customIdValue, $isb64 = false){
$customId no debe ser bool, se debe especificar siempre porque esa es la naturaleza de Timbrado V4, recomiendo hacer un helper que valide los parametros customId, email

2022-11-10 20:23 UTC, SwAeyrton commented on SWServices/Stamp/StampService.php
> +    public static function StampV4CustomEmail($xml, $customId = true, $customIdValue , $email = true, $emailAddress, $isb64 = false){
Igual aqui veo innecesario recibir un bool

2022-11-10 20:23 UTC, SwAeyrton commented on SWServices/Stamp/StampService.php
> +    public static function StampV4CustomPdfEmail($xml, $customId = true, $customIdValue, $pdf = true , $email = true, $emailAddress, $isb64 = false){
Deberian existir solo 2 metodos por cada version de respuesta, uno que solo reciba customId y pueda generar el PDF, y otro que envie correos (este ultimo genera el PDF ya por lo que no seria necesario especificar el header PDF)

2022-11-10 20:23 UTC, SwAeyrton commented on SWServices/Stamp/StampService.php
> +        return StampRequestV4::sendReqV4(Services::get_url(), Services::get_token(), $xml, "v4", $isb64, Services::get_proxy(), '/v4/cfdi33/stamp/', false, NULL, true, true, $emailAddress);
Solo estas usando la version 4 de respuesta.

2022-11-15 18:27 UTC, SwAeyrton requested changes

2022-11-15 18:27 UTC, SwAeyrton commented on SWServices/Stamp/StampService.php
> +    public static function StampV4CustomIdPdfV1($xml, $customId, $isb64 = false){
Falta el parametro $pdf = false para que el cliente pueda especificar si desea generar el PDF

2022-11-15 18:27 UTC, SwAeyrton commented on composer.json
>              "guzzlehttp/guzzle": "^7.3"
Falta actualizar la version

2022-11-15 18:28 UTC, ReyesSW commented on README.md
> +        "user"=>"pruebas_ut@sw.com.mx",
Ya realice un cambio, quite las credenciales , por solo cuentaUsuario y contraseña

2022-11-15 19:36 UTC, ReyesSW commented on composer.json
>              "guzzlehttp/guzzle": "^7.3"
Version modificada, aunque dependiendo de quien haga merge primero debera modificarse.

2022-11-15 19:37 UTC, ReyesSW commented on SWServices/Stamp/StampService.php
> +    public static function StampV4CustomIdPdfV1($xml, $customId, $isb64 = false){
Ya se manda el PDF si no se especifica como true, queda como false por defecto.

2022-11-16 00:13 UTC, SwAeyrton requested changes

2022-11-16 00:13 UTC, SwAeyrton commented on SWServices/Stamp/StampHelper.php
> +    public function __construct($params)
las funciones son static , realmente no necesitas un constructor

2022-11-16 00:13 UTC, SwAeyrton commented on SWServices/Stamp/StampRequest.php
> +         $customId = ($customId == NULL || $customId == "")?NULL:"customid: ".$customId."',";
condicional innecesario porque customId siempre deberia tener un valor

2022-11-16 00:13 UTC, SwAeyrton commented on SWServices/Stamp/StampRequest.php
> +         $email = ($email == NULL || $email == "")?NULL:"'email: ".$email."',";
lo mejor es que en los parametros ya este asignado por default email como null y estas asignaciones son innecesarias.

2022-11-16 00:13 UTC, SwAeyrton commented on SWServices/Stamp/StampService.php
> +        $helper = new StampHelper($params);
esto es innecesario dado que las funciones son static

2022-11-16 00:13 UTC, SwAeyrton commented on SWServices/Stamp/StampService.php
> +    public static function stampV4CustomIdPdfV1($xml, $customId, $pdf ,$isb64 = false){
$pdf deberia estar como false por default, asi no forzas al cliente que te mande un false cuando no quiera generar el PDF, solo te mandaria los dos primeros parametros.

2022-11-16 00:13 UTC, SwAeyrton commented on SWServices/Stamp/StampRequest.php
> +            $customId.$pdf.$email
Esto realmente funciona? creo que en las UT deberias agregar una prueba que timbre el comprobante y ver si te genera el pdf y te hace el reenvio de los mails

2022-11-16 00:13 UTC, SwAeyrton commented on composer.json
>              "guzzlehttp/guzzle": "^7.3"
Ya se actualizo develop. la version es otra, debes jalarte los cambios.

2022-11-18 22:36 UTC, ReyesSW commented on SWServices/Stamp/StampHelper.php
> +    public function __construct($params)
Elimine el construct

2022-11-18 22:36 UTC, ReyesSW commented on SWServices/Stamp/StampRequest.php
> +         $customId = ($customId == NULL || $customId == "")?NULL:"customid: ".$customId."',";
Deje solo la construccion de un string para recibir parametros en el header del request.

2022-11-18 22:37 UTC, ReyesSW commented on SWServices/Stamp/StampService.php
> +    public static function stampV4CustomIdPdfV1($xml, $customId, $pdf ,$isb64 = false){
Se envia como false

2022-11-22 18:56 UTC, SwAeyrton requested changes

2022-11-22 18:56 UTC, SwAeyrton commented on SWServices/Stamp/StampService.php
> +    public static function stampV4CustomIdEmailV2($xml, $customId, $pdf = false, $email, $isb64 = false){
Aqui ya no es necesario el parametro pdf porque especificar email ya genera por defecto el pdf.

2022-11-22 18:56 UTC, SwAeyrton commented on README.md
> +<<<<<<< HEAD
Se te fueronestos datos.

2022-11-22 18:56 UTC, SwAeyrton commented on SWServices/Stamp/StampHelper.php
> +                        $i++;
Porque tienes una variable aumentandose de valor en lugar de directamente hacer un break o un return

2022-11-22 18:58 UTC, SwAeyrton requested changes

2022-11-22 18:58 UTC, SwAeyrton commented on composer.json
> +}
Falta actualizar la version.

2022-11-22 23:22 UTC, ReyesSW commented on SWServices/Stamp/StampService.php
> +    public static function stampV4CustomIdEmailV2($xml, $customId, $pdf = false, $email, $isb64 = false){
Si se envia el parametro de email el pdf se recibe por default

2022-11-22 23:29 UTC, ReyesSW commented on SWServices/Stamp/StampHelper.php
> +                        $i++;
Se elimina la variable en aumento y se manda un false--> si existe false regresa error y un var_dump del parametro email

2022-11-22 23:30 UTC, ReyesSW commented on composer.json
> +}
Se actualiza la version.

2022-11-22 23:38 UTC, ReyesSW commented on README.md
> +<<<<<<< HEAD
Ya acepte los cambios que venian de develop para el readme

2022-11-23 00:30 UTC, SwAeyrton approved these changes

2022-11-23 16:46 UTC, marifersw approved these changes

2022-11-23 16:48 UTC, FerCarrilloM approved these changes

2022-11-23 22:01 UTC, merged