Feature/v4 issue
lunasoft/sw-sdk-php pull request #47
Opened 2022-12-05 23:47 UTC by ReyesSW

Se crea la rama y se modifican archivos para el timbrado V4 Issue.

2022-12-06 00:27 UTC, SwAeyrton requested changes

2022-12-06 00:27 UTC, SwAeyrton commented on SWServices/Stamp/StampService.php
> +    public static function stampV4CustomIdIssueEmailV4($xml, $customId, $email, $isb64 = false){
El nombre deberia ser issueV4CustomIdEmailV4

2022-12-06 00:27 UTC, SwAeyrton commented on Test/StampTests.php
> +		public function testStampV4IssueCustomIdPdf()
Faltan UT de error

2022-12-08 14:56 UTC, ReyesSW commented on SWServices/Stamp/StampService.php
> +    public static function stampV4CustomIdIssueEmailV4($xml, $customId, $email, $isb64 = false){
Se modifica para que todo este en la carpeta issue

2022-12-08 16:18 UTC, FerCarrilloM approved these changes

2022-12-08 19:14 UTC, SwAeyrton requested changes

2022-12-08 19:14 UTC, SwAeyrton commented on SWServices/Issuer/IssuerService.php
> +    public static function stampV4CustomIdPdfV1($xml, $customId, $pdf = false ,$isb64 = false){
Falta generar la documentacion de los metodos publicos con PHPDoc

2022-12-08 19:15 UTC, SwAeyrton commented
Falta agregar la documentacion en el readme

2022-12-08 23:15 UTC, martinfnsw commented on SWServices/Issuer/IssuerService.php
> +        $helper = new StampHelper($params);
No es necesario enviar parámetros al instanciar la clase stamphelper ya que no tiene constructor

2022-12-13 00:09 UTC, SwAeyrton requested changes

2022-12-13 00:09 UTC, SwAeyrton commented on SWServices/Issuer/IssuerService.php
> +    //Funcion que recibe el CustomId y timbra el XML con version V4 de respuesta
No es correcta la documentación, https://docs.phpdoc.org/3.0/guide/references/phpdoc/basic-syntax.html#basic-syntax

2022-12-13 02:05 UTC, ReyesSW commented on SWServices/Issuer/IssuerService.php
> +    //Funcion que recibe el CustomId y timbra el XML con version V4 de respuesta
Utilizo la sintaxis de phpdoc para comentar el IssuerService

2022-12-13 17:36 UTC, SwAeyrton requested changes

2022-12-13 19:09 UTC, ReyesSW commented on SWServices/Issuer/IssuerService.php
> +     *  * @autor David Ernesto Reyes <david.reyes@sw.com.mx>
Valide la documentacion de Java PdfService que tenia mas de una funcion.

2022-12-13 22:51 UTC, SwAeyrton approved these changes

2022-12-13 22:52 UTC, ReyesSW commented on SWServices/Issuer/IssuerService.php
> +        $helper = new StampHelper($params);
Se elimina enviar parametros

2022-12-13 23:35 UTC, martinfnsw approved these changes

2022-12-14 02:20 UTC, ReyesSW commented on SWServices/Issuer/IssuerService.php
> +     * @param string xml $xml documento a timbrar.
Ya se corrigio la duplicidad de texto

2022-12-14 02:41 UTC, merged