Feature Storage Service
lunasoft/sw-sdk-php pull request #48
Opened 2022-12-08 18:09 UTC by martinfnsw

Se agrega servicio de recuperar xml por UUID
Se agrega UT para recuperar por xml
Se actualiza readme

2022-12-08 19:00 UTC, SwAeyrton requested changes

2022-12-08 19:48 UTC, ReyesSW approved these changes

2022-12-08 19:49 UTC, FerCarrilloM approved these changes

2022-12-08 22:13 UTC, martinfnsw commented on SWServices/Storage/StorageRequest.php
> +
gracias, quité unas lineas de más

2022-12-09 20:21 UTC, marifersw approved these changes

2022-12-09 22:17 UTC, merged