Se sube la version y se agregan referencias
lunasoft/sw-sdk-php pull request #54
Opened 2023-03-27 23:50 UTC by ReyesSW

Se sube la version para el cambio y se agrean las referencias que generaban error.

2023-03-28 00:05 UTC, SebastianSW approved these changes

2023-03-28 15:41 UTC, marifersw approved these changes

2023-03-28 16:39 UTC, martinfnsw requested changes

2023-03-28 16:39 UTC, martinfnsw commented on composer.json
> +    "version": "1.0.9.1",
En hotfix se sube el último digito 
https://smarterweb.atlassian.net/wiki/spaces/SO/pages/1734180865/Gitflow

2023-03-28 17:05 UTC, ReyesSW commented on composer.json
> +    "version": "1.0.9.1",
Listo se modifica a 1.0.8.2 para el hotfix.

2023-03-31 23:03 UTC, martinfnsw approved these changes

2023-03-31 23:04 UTC, merged