Hotfix/methods cancelation
lunasoft/sw-sdk-php pull request #62
Opened 2023-10-04 02:22 UTC by marifersw

2023-10-04 16:00 UTC, SebastianSW commented on SWServices/Cancelation/CancelationService.php
> +            $foliosustitucion
Mismo caso que el comentario anterior, para $foliosustitucion y $action en donde aplique valor null

2023-10-04 16:22 UTC, SebastianSW commented on Test/CancelationTests.php
> +			echo ($result);
Sería mejor cambiar los echo por var_dump o por un echo json_encode($result), ya que echo por si solo no puede mostrar un objeto

2023-10-04 16:25 UTC, SebastianSW commented on index.php
> +    $cancelationResult = CancelationService::CancelationByUUID($rfc, $uuid, $motivo);
Hace falta los llamado al método CancelationService::Set($params);

2023-10-04 18:16 UTC, SebastianSW approved these changes

2023-10-04 18:25 UTC, FerCarrilloM approved these changes

2023-10-04 23:12 UTC, martinfnsw requested changes

2023-10-04 23:12 UTC, martinfnsw commented on SWServices/Cancelation/CancelationRequest.php
> +    public static function sendReqUUID($url, $token, $rfc, $uuid, $motivo,  $proxy, $service, $foliosustitucion = null, $action = null)
No veo necesario declarar action

2023-10-04 23:12 UTC, martinfnsw commented on SWServices/Cancelation/CancelationService.php
> +    {
Cuidar los espacios

2023-10-04 23:30 UTC, marifersw commented on SWServices/Cancelation/CancelationRequest.php
> +    public static function sendReqUUID($url, $token, $rfc, $uuid, $motivo,  $proxy, $service, $foliosustitucion = null, $action = null)
Lo que sucede es que esta request se usa tambien para el servicio de Aceptacion y Rechazo por UUID, por ello se coloca action

2023-10-05 00:05 UTC, martinfnsw commented on SWServices/Cancelation/CancelationRequest.php
> +    public static function sendReqUUID($url, $token, $rfc, $uuid, $motivo,  $proxy, $service, $foliosustitucion = null, $action = null)
sip pero no pasa nada si no se manda el parámetro ya que está declarado como opcional

2023-10-05 00:22 UTC, martinfnsw approved these changes

2023-10-05 00:30 UTC, ReyesSW approved these changes

2023-10-05 00:42 UTC, merged