feature/SS-245
lunasoft/sw-sdk-php pull request #72
Opened 2024-02-13 17:26 UTC by SebastianSW

- Implementación del método Emisión Timbrado JSON V4
- Se permite el envío de parámetros adicionales: CustomId, Email y Pdf en los métodos
- Incorporación de UT´s para validar los nuevos métodos
- Se actualiza README
- Correcciones menores

2024-02-13 17:56 UTC, SwAeyrton requested changes

2024-02-13 17:56 UTC, SwAeyrton commented on SWServices/JSonIssuer/JsonIssuerHelper.php
> +            if ($customId != NULL || $customId != "") {
haria falta nada mas validar la longitud, no estoy muy seguro pero creo que lo maximo que acepta el servicio son 150 caracteres

2024-02-13 17:56 UTC, SwAeyrton commented on SWServices/JSonIssuer/JsonIssuerService.php
> +{
es mejor separar estos servicios asi como se hace en las otras librerias, es decir, crear una clase que sea especial para el timbrado V4

2024-02-13 19:47 UTC, SebastianSW commented on SWServices/JSonIssuer/JsonIssuerHelper.php
> +            if ($customId != NULL || $customId != "") {
Se mejora la validación de customId vacío o nulo y se agrega validación de máximo de caracteres 100 como se indica en la librería de NetStandard
![image](https://github.com/lunasoft/sw-sdk-php/assets/119515416/89d1e6a4-57c9-4ff7-a574-16f57425a673)

2024-02-13 19:47 UTC, SebastianSW commented on SWServices/JSonIssuer/JsonIssuerService.php
> +{
Se separan los métodos, se corrigen UT y README con estos cambios

2024-02-13 22:12 UTC, SwAeyrton approved these changes

2024-02-13 23:08 UTC, FerCarrilloM approved these changes

2024-02-13 23:38 UTC, marifersw approved these changes

2024-02-14 01:14 UTC, martinfnsw requested changes

2024-02-14 01:14 UTC, martinfnsw commented on SWServices/JSonIssuer/JsonIssuerRequest.php
> +		$path = "/v3/cfdi33/issue/json/";
me parece que no es el path de v4

2024-02-14 01:37 UTC, SebastianSW commented on SWServices/JSonIssuer/JsonIssuerRequest.php
> +		$path = "/v3/cfdi33/issue/json/";
La función de sendReq es para emisión timbrado JSON, esta ya existía, se realizó ajustes al codigo para mejor escalabilidad, se dejó el path fijo para no afectar a los usuarios que consumen el método así, el path para timbrado V4 están en el archivo SWServices/JSonIssuer/JsonIssuerV4Service.php, este se pasa como parámetro al método para su consumo
![image](https://github.com/lunasoft/sw-sdk-php/assets/119515416/2cdff27a-818f-4386-9ba1-aca73403ba8d)

2024-02-14 16:22 UTC, merged