feature/SS-731
lunasoft/sw-sdk-php pull request #77
Opened 2024-12-20 01:36 UTC by SebastianSW

- TLS 1.2 | 1.3
- HTTP a HTTPS
- API Autenticación V2
- API Usuarios V2
- API Balance V2
- Actualización de README.md
- Se sube versión

> [!NOTE]
> Se sube versión type minor por la cantidad de cambios realizados

2024-12-20 16:47 UTC, FerCarrilloM requested changes

2024-12-20 16:47 UTC, FerCarrilloM commented on index.php
Creo que hace falta actualizar el Index.
Ya que hay métodos que no existen u otros cuyas referencias se actualizaron

2024-12-20 17:22 UTC, FerCarrilloM approved these changes

2024-12-20 17:24 UTC, SebastianSW commented on index.php
Gracias Nano, se actualiza el index para las nuevas referencias

2024-12-27 19:53 UTC, marifersw approved these changes

2024-12-30 16:51 UTC, martinfnsw approved these changes

2024-12-30 16:54 UTC, Reyes-SW approved these changes

2024-12-30 17:13 UTC, merged